server:
  port: 8761 # Porta padrão do Eureka

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # Ele não precisa se registrar nele mesmo
    fetch-registry: false       # Ele não precisa buscar o registro dele mesmo
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://localhost:9411/api/v2/spans
